### ISSUE TITLE
Find  a unified tool for public documentation or "Community Guide"

### ISSUE THREAD

**Issue by colombene** [zinc-collective/zinc.coop#61] opened 2020-11-13 01:20 UTC
It would be nice to put Zinc's documentation in one place like [Enspiral's Handbook](https://handbook.enspiral.com/). Many use [Gitbook](https://www.gitbook.com/) but it's $8 per contributor. Would love dev input on something we can implement with multiple editors. @anaulin mentioned [BookStack](https://www.bookstackapp.com/).

**Comment by anaulin** [comment] 2020-11-13 03:11
It would be good to agree on what are our requirements for such a tool. At first glance, I think we want something like:

### Must-haves
* available on the web, publicly readable
  * do we need to have the ability to have "private" sections? or is it ok to do such stuff in Google Drive?
* easily editable for non-developers, which means a web UI for editing (i.e. a static site with mardkown that gets checked into GitHub is not it)
  * includes being able to organize pages / sections
* some way to organize content and inter-link it, to make docs more findable (lack of this seems like the main drawback of Google Docs)
* affordable ($8/mo/contributor feels like too much)

### Nice-to-haves
* some kind of change history or versioning
* ability to "tag" other contributors for review or comment
* looks nice

Anything else? Anything that needs to move sections?

**Comment by anaulin** [comment] 2020-11-13 03:14
After doing a bit of research, here is a list of possible tools we could try, with my briefs notes on pros/cons:

  * GitHub Wiki (https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/documenting-your-project-with-wikis). We could create a "community guide" repo and use it only for its wiki functionality.
    * Pros
      * Simple, already "there", ready to start using at no added cost.
    * Cons
      * Not the most fully-featured wiki software, nor the most esthetically pleasing.
      * Ties us into GitHub, requires everybody that contributes to the guide to have a GitHub login.
  * BookStack (https://www.bookstackapp.com/), PHP+Laravel based. Similar to GitBook, organizes content in "books".
    * Pros
      * Looks simple, can be made fully private, if we preferred that (i.e. it would be for Zinc members/contributors only).
    * Cons
      * Self-hosting necessary.
  * MediaWiki (https://www.mediawiki.org/wiki/MediaWiki), the software that powers Wikipedia, PHP-based.
    * Pros
      * Very familiar.
    * Cons
      * Self-hosting necessary.
      * Feels a little old skool?
  * Wiki.js (https://wiki.js.org/), Node-based modern wiki.
    * Pros
      * Looks modern, has more customizable look & feel than e.g. Media Wiki.
      * Has "deploy on Heroku" templates for easy self-hosting, as well as for other platforms (https://docs.requarks.io/install/heroku)
    * Cons
      * Self-hosting necessary.

**Comment by colombene** [comment] 2020-11-13 06:18
Your requirements capture the gist for me.

**Comment by zspencer** [comment] 2020-11-15 00:31
Something to keep in mind is Zinc's core purpose is to operate, develop, and maintain worker-and-consumer-owned digital products and services. As a result, my preference is to lean towards self-hosting pieces of infrastructure that can be plugged into a higher-order platform (Such as Convene or Wordpress). 

I think there are two ways we can approach that:

1. Spin up a full-wiki project that has a solid API and begin using "as is" while learning enough about it that we can hook them into a higher-order platform like Convene
2. Assemble something a bit more piecemeal and build it into Convene, perhaps by leveraging [ActionText](https://edgeguides.rubyonrails.org/action_text_overview.html) for editing and then setting up www.zinc.coop as a Space within Convene.

My gut prefers option 1 if we want to prioritize resolving the pain point of "folks who aren't programmers are  gatekept from contributing to the public presentation of Zinc."

That said, option 2 is preferred if we want to focus on the long-term benefit of creating a community-owned platform for small organizations, clubs, and cooperatives.

I'm happy either way, but my programmer's heart prefers option 2.

**Comment by colombene** [comment] 2020-12-01 01:38
I'm leaning towards Github for now and option 1 above. Just wanna get the content together and out more quickly.

**Comment by anaulin** [comment] 2020-12-01 22:45
I think it makes sense to focus on the content first. We can always migrate the text itself later.

I've set up a new GitHub repo to host the wiki for now: https://github.com/zinc-collective/community-guide/wiki

I added the zinc contributors team as maintainers on that repo, so everyone should be able to edit the content. @colombene holler if you can't get access and I can help get things sorted.

**Comment by anaulin** [comment] 2020-12-07 00:11
In my earlier comment capturing requirements I put "ability to tag other contributors for review" as "Nice to Have", but it is starting to feel like some kind of review flow is maybe a "must have" for us, as we're bumping into this trying to use GitHub Wiki but not having a good way to do a "draft" and then run it by other people.

**Comment by zspencer** [comment] 2020-12-07 18:29
I'm curious about what is prompting the desire for a review step? Is it because we're worried about publishing information that's invalid? Or is it because we want to feel like the information that was changed is in other people's heads?

I, personally, really like review steps in my work-process, and having that tightly integrated into how we publish the community guide feels useful to me.

However, I also think that sharing a google doc with the changes highlighted, or directly publishing the results and asking folks to do a quick read through and paying special attention to the pieces that had the most change are viable techniques for review.

That said, if the issue is more about "I don't know if I'm making changes the changes that I _should_" I think there's more to dive into there. If it feels like changes are high stakes; then I would love if we invested some of our energy into reducing the stakes. 

The way I think of "lowering the stakes" is through building cohesive harmony along the following four axis:

1. Philosophy ("Why are we doing this?")
2. Strategy ("Where are we going?")
3. Tactics ("What will get us there?")
4. Techniques ("How will we do it?")

In my head, the _Philosophy_ is so we can pull in co-conspirators and plug them into Zinc projects. 

The _Strategy_ is by building a vibrant community of participants and contributors. 

The _Tactic_ of a Community Guide is so the folks who prefer to read to understand something concrete have access to accurate, concise information enabling and supporting their first few contributions.

If we can hold the Philosophy, Strategy and Tactics; then the _Technique_ of having a Review Step continues to feel like a "nice to have." Perhaps an alternative would be to hold these intents more clearly by placing them on the landing page of the Wiki? To that end, I've taken a brief stab here: https://github.com/zinc-collective/community-guide/wiki/Community-Guide-Introduction/35868c921a2e3c446002b72481ef2366fbfa10d3

**Comment by colombene** [comment] 2020-12-07 20:58
I think it's great to discuss the goals and purpose. Esp. because I realize I think of it a differently than what's stated ;). I think all members of the community would be the stakeholders in different ways, not just new people or onboards. This community is in a lot of flux and this can be a way to surface and hopefully engage with what's happening. So this info could be sent out to regularly to inform everyone and (hopefully) confirmed or revised. People who have figured out a good practice or resource can also add it. People who want to change how things are done can refer to the current practice here and make a proposal. But even that kind of change proposal would require more clarity and alignment on how different people *think* things are done in the first place. Good ideas and initiatives come up all the time (Slack, email, a meeting, etc.) but slip away and institutional knowledge resides with individuals who happen to hear it and pass it on. Efforts get lost or duplicated or misunderstood or die out prematurely from lack of support.

As an example, look at tools. If we took the time to understand what everyone uses and how they use it we can record it. We can note what we use "officially" as a group and what people use on their own. Once we know that, maybe we can see there's duplication and abandonment. Or someone could propose switching to different co-op built tools and the group could vote on it. And when new people come, they'd know what we use and what we use it for. It might even help community connections as people identify others who do similar work.

I believe the goal is to attract and support a diverse array of people who might want to work on vastly different things. The current loose system probably puts a lot of burden on individuals (like Zee) and won't scale. I also tend to think what is documented or assumed skews towards experienced programmers who want to freely contribute feedback or code in an open source/github-centric way. Other kinds of work and experiences may need other/different kinds of support.

This is the vision I'm working from and can work on a purpose statement, do a draft of the guide (some info will be placeholder and dependent on input or decisions) and send it out regularly (~monthly?) for input. Still thinking - should we stick with Github Wiki? I'm sorta leaning towards google docs, maybe for the pre-release draft. Or are there collaborative edit tools I'm missing for the Wiki?

**Comment by zspencer** [comment] 2020-12-07 22:46
> I believe the goal is to attract and support a diverse array of people who might want to work on vastly different things. The current loose system probably puts a lot of burden on individuals (like Zee) and won't scale.  

Agreed! 


> I also tend to think what is documented or assumed skews towards experienced programmers who want to freely contribute feedback or code in an open source/github-centric way.

I agree, and I would love to figure out a way to de-center the programmer archetype. I also think the Github Wiki doesn't play nicely with thins like Adobe XD or Miro or other design tools.

> This is the vision I'm working from and can work on a purpose statement, do a draft of the guide (some info will be placeholder and dependent on input or decisions) and send it out regularly (~monthly?) for input.

I think this is a valid strategy; and I'll do my best to read and respond to changes in a timely manner.


> Still thinking - should we stick with Github Wiki? I'm sorta leaning towards google docs, maybe for the pre-release draft. Or are there collaborative edit tools I'm missing for the Wiki?

I don't believe you're missing things with the Wiki; but there may be something magical that @anaulin knows that I don't about having conversations around edits before they're applied. I'm 100% in favor of us using the structures that you find most comfortable and convenient.

**Comment by anaulin** [comment] 2020-12-08 04:24
> > Still thinking - should we stick with Github Wiki? I'm sorta leaning towards google docs, maybe for the pre-release draft. Or are there collaborative edit tools I'm missing for the Wiki?

> I don't believe you're missing things with the Wiki; but there may be something magical that @anaulin knows that I don't about having conversations around edits before they're applied. I'm 100% in favor of us using the structures that you find most comfortable and convenient.

I poked around and couldn't find anything. You can do commits to the wiki from the command line, but not set up PRs that you can discuss (or at least I didn't see how). 😞 

I really want to make some time to explore some of the other tools in the list above and see if that would be a better fit. For now we can use Google Docs for discussion, if that's easier. (And we can migrate content automatically from the Github Wiki into another tool later, since it is a GitHup repo that is essentially a set of Markdown files.)

**Comment by anaulin** [comment] 2020-12-12 22:18
I did a little bit more of researching around this, and none of the tools in this category seem to have "comments" or "draft-and-review-before-publish" functionality.

At Ampled, if there is a change that we can to make to something in the public docs, which are on GitBook (e.g. say we are modifying https://docs.ampled.com/coop/ownership-classes), there is a process where we all comment in a Google Doc and then once the changes are agreed upon by all, it gets copied into GitBook. So it seems like there is no magic bullet to solve this particular use case.

Coming back to the broader conversation of which tool to use for the long term, I am wondering what is a good way to balance our own needs with what might be a good fit to sell as a component of Convene.

I imagine that if I was a small group wanting to have an online space, I'd want something flexible like a wiki, where members could have sections for their own notes, we could have less-polished pages with e.g. meeting notes, working docs, etc. For this use case, something like GitBook or even Grav feels a little too heavyweight, too much geared towards "make a finished product to put on the web". But it seems that this is what we'd like for our own Community Guide, which is more of a "published to the world / ourselves" product. So I'm not sure if we should be trying to split the difference or if we are really thinking about two separate products / features.

All that said, I also think that, given our limited capacity, we are probably overthinking this to death, and we should first focus on serving our own need to the Community Guide, and not try to be solving all the problems at once. In that spirit, I propose that the next step on this issue to "find a tool for our Community Guide" be me or someone else doing a quick spike to self-host a GitBook, playing with it to see how it feels, then iterating from there. (I'm picking GitBook because it seems widely used by similar orgs and seems likely to fit our needs; Grav looks really nice too, but perhaps playing with Grav is a "nice to have" at this point).

**Comment by zspencer** [comment] 2020-12-13 20:23
I like the instinct to focus the Community Guide on our internal needs. Instead of a spike (which, by all means, feel free to do!) maybe that means we continue to rely on Google Docs with public read and group-level comment/edit access?

**Comment by anaulin** [comment] 2020-12-13 21:49
> maybe that means we continue to rely on Google Docs with public read and group-level comment/edit access?

Yep, I think this is the way to go for now. We can always migrate the content later, but using Google Docs lets us essentially have a workable, publishable thing with content that we can iterate on / review / comment easily for now.

**Closed as completed** 2022-09-23 21:19 UTC
